# Generated by Django 6.0.6 on 2026-07-20 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0002_alter_parcel_status_consolidation'),
        ('payments', '0002_payment_payment_url_payment_provider_raw_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='parcels.order'),
        ),
    ]
