# Generated by Django 6.0.6 on 2026-07-26 21:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_payment_options_alter_paymentmethod_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'verbose_name': 'MÃ©thode de paiement', 'verbose_name_plural': 'MÃ©thodes de paiement'},
        ),
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='XOF', max_length=10, verbose_name='Devise'),
        ),
        migrations.AddField(
            model_name='payment',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='TÃ©lÃ©phone'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de crÃ©ation'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.paymentmethod', verbose_name='MÃ©thode'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider_raw_response',
            field=models.JSONField(blank=True, null=True, verbose_name='RÃ©ponse brute du fournisseur'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reference',
            field=models.CharField(max_length=100, unique=True, verbose_name='RÃ©fÃ©rence'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('completed', 'TerminÃ©'), ('failed', 'Ã‰chouÃ©'), ('cancelled', 'AnnulÃ©')], default='pending', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='DerniÃ¨re mise Ã\xa0 jour'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='icon_url',
            field=models.URLField(blank=True, null=True, verbose_name="URL de l'icÃ´ne"),
        ),
        migrations.CreateModel(
            name='SavedPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='Type')),
                ('label', models.CharField(max_length=100, verbose_name='LibellÃ©')),
                ('last_four', models.CharField(blank=True, max_length=4, null=True, verbose_name='4 derniers chiffres')),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='TÃ©lÃ©phone')),
                ('is_default', models.BooleanField(default=False, verbose_name='Par dÃ©faut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de crÃ©ation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_payment_methods', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Moyen de paiement enregistrÃ©',
                'verbose_name_plural': 'Moyens de paiement enregistrÃ©s',
                'ordering': ['-created_at'],
            },
        ),
    ]
