# Generated by Django 6.0.6 on 2026-09-06 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_paymentmethod_options_payment_currency_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'verbose_name': 'Méthode de paiement', 'verbose_name_plural': 'Méthodes de paiement'},
        ),
        migrations.AlterModelOptions(
            name='savedpaymentmethod',
            options={'ordering': ['-created_at'], 'verbose_name': 'Moyen de paiement enregistré', 'verbose_name_plural': 'Moyens de paiement enregistrés'},
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.paymentmethod', verbose_name='Méthode'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider_raw_response',
            field=models.JSONField(blank=True, null=True, verbose_name='Réponse brute du fournisseur'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reference',
            field=models.CharField(max_length=100, unique=True, verbose_name='Référence'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('completed', 'Terminé'), ('failed', 'Échoué'), ('cancelled', 'Annulé')], default='pending', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='icon_url',
            field=models.URLField(blank=True, null=True, verbose_name="URL de l'icône"),
        ),
        migrations.AlterField(
            model_name='savedpaymentmethod',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='savedpaymentmethod',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Par défaut'),
        ),
        migrations.AlterField(
            model_name='savedpaymentmethod',
            name='label',
            field=models.CharField(max_length=100, verbose_name='Libellé'),
        ),
        migrations.AlterField(
            model_name='savedpaymentmethod',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Téléphone'),
        ),
    ]
