# Generated by Django 6.0.6 on 2026-09-12 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_ensure_checkout_payment_methods'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='proof_image',
            field=models.ImageField(blank=True, null=True, upload_to='payments/proofs/%Y/%m/', verbose_name='Preuve (capture)'),
        ),
    ]
