# Generated by Django 6.0.6 on 2026-09-13 09:04

from django.db import migrations, models


def forwards_xof_to_fcfa(apps, schema_editor):
    Payment = apps.get_model('payments', 'Payment')
    Payment.objects.filter(currency__iexact='XOF').update(currency='FCFA')


def backwards_fcfa_to_xof(apps, schema_editor):
    Payment = apps.get_model('payments', 'Payment')
    Payment.objects.filter(currency__iexact='FCFA').update(currency='XOF')


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_payment_proof_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='FCFA', max_length=10, verbose_name='Devise'),
        ),
        migrations.RunPython(forwards_xof_to_fcfa, backwards_fcfa_to_xof),
    ]
