# Generated by Django 6.0.6 on 2026-09-12 05:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='stars',
            field=models.PositiveSmallIntegerField(default=0, help_text='Notation admin : 0 = non noté, 1 à 5 = niveau client.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Étoiles client (0–5)'),
        ),
    ]
