# Generated by Django 6.0.6 on 2026-09-08 10:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinary_rate_per_kg', models.DecimalField(decimal_places=2, default=Decimal('17.00'), max_digits=10, verbose_name='Colis ordinaire — $/kg')),
                ('ordinary_days', models.PositiveSmallIntegerField(default=21, verbose_name='Colis ordinaire — délai (jours)')),
                ('express_available', models.BooleanField(default=False, verbose_name='Express disponible')),
                ('express_rate_per_kg', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Express — $/kg')),
                ('express_days', models.PositiveSmallIntegerField(default=8, verbose_name='Express — délai (jours)')),
                ('sensitive_rate_per_kg', models.DecimalField(decimal_places=2, default=Decimal('25.00'), max_digits=10, verbose_name='Colis sensibles — $/kg')),
                ('sensitive_days', models.PositiveSmallIntegerField(default=21, verbose_name='Colis sensibles — délai (jours)')),
                ('sensitive_note', models.CharField(default='batterie, liquide, médicaments, perruque, montres, cosmétique', max_length=255, verbose_name='Colis sensibles — exemples')),
                ('phone_flat_fee', models.DecimalField(decimal_places=2, default=Decimal('36.00'), max_digits=10, verbose_name='Téléphone — forfait $')),
                ('phone_days', models.PositiveSmallIntegerField(default=21, verbose_name='Téléphone — délai (jours)')),
                ('grouping_flat_max_kg', models.DecimalField(decimal_places=2, default=Decimal('4.00'), max_digits=10, verbose_name='Groupage forfait — poids max (kg)')),
                ('grouping_flat_fee', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=10, verbose_name='Groupage forfait — $ (1–4 kg)')),
                ('grouping_rate_per_kg', models.DecimalField(decimal_places=2, default=Decimal('2.50'), max_digits=10, verbose_name='Groupage — $/kg (≥ 5 kg)')),
                ('usd_to_cdf', models.DecimalField(decimal_places=4, default=Decimal('2270.0000'), max_digits=12, verbose_name='1 USD → CDF (Fc)')),
                ('usd_to_gbp', models.DecimalField(decimal_places=6, default=Decimal('0.790000'), max_digits=12, verbose_name='1 USD → GBP (£)')),
                ('usd_to_xof', models.DecimalField(decimal_places=4, default=Decimal('600.0000'), max_digits=12, verbose_name='1 USD → FCFA (XOF)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètres tarifs',
                'verbose_name_plural': 'Paramètres tarifs',
            },
        ),
    ]
