# Generated by Django 6.0.6 on 2026-09-12 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssettings',
            name='china_warehouse_phone',
            field=models.CharField(default='18575740344', max_length=50, verbose_name='Entrepôt Chine — téléphone'),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='china_warehouse_street',
            field=models.CharField(default='佛山市南海区狮山镇塘头村一队新一巷3号bujito', max_length=500, verbose_name='Entrepôt Chine — adresse'),
        ),
    ]
