# Generated by Django 6.0.6 on 2026-09-13 09:27

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_china_warehouse_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesssettings',
            name='usd_to_xof',
            field=models.DecimalField(decimal_places=4, default=Decimal('600.0000'), max_digits=12, verbose_name='1 USD → FCFA'),
        ),
    ]
