# Generated by Django 6.0.6 on 2026-10-05 14:39

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0008_air_sea_addresses'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssettings',
            name='alipay_wechat_recharge_fee_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('15.87'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Frais recharge Alipay / WeChat Pay (%)'),
        ),
    ]
