# Generated by Django 6.0.6 on 2026-10-05 14:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0009_businesssettings_alipay_wechat_recharge_fee_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssettings',
            name='computer_flat_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=10, verbose_name='Ordinateur — forfait par pièce $'),
        ),
    ]
