# Generated by Django 6.0.6 on 2026-06-11 05:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('in_transit', 'En transit'), ('out_for_delivery', 'En cours de livraison'), ('delivered', 'Livré'), ('exception', 'Exception'), ('consolidated', 'Consolidé')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='Consolidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En traitement'), ('completed', 'Terminé'), ('cancelled', 'Annulé')], default='pending', max_length=20)),
                ('parcels', models.ManyToManyField(related_name='consolidations', to='parcels.parcel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consolidations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Groupage',
                'verbose_name_plural': 'Groupages',
                'ordering': ['-request_date'],
            },
        ),
    ]
