# Generated by Django 6.0.6 on 2026-07-26 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0002_alter_parcel_status_consolidation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='client_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom du client'),
        ),
        migrations.AddField(
            model_name='parcel',
            name='client_phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Téléphone client'),
        ),
        migrations.AddField(
            model_name='parcel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='parcels/', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='parcel',
            name='warehouse_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='N° Entrepôt'),
        ),
        migrations.AddField(
            model_name='parcel',
            name='weight_volume',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Poids/Volume'),
        ),
        migrations.AlterField(
            model_name='consolidation',
            name='parcels',
            field=models.ManyToManyField(related_name='consolidations', to='parcels.parcel', verbose_name='Colis'),
        ),
        migrations.AlterField(
            model_name='consolidation',
            name='request_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de demande'),
        ),
        migrations.AlterField(
            model_name='consolidation',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('processing', 'En traitement'), ('completed', 'Terminé'), ('cancelled', 'Annulé')], default='pending', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='consolidation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consolidations', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de commande'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('processing', 'En traitement'), ('shipped', 'Expédiée'), ('delivered', 'Livrée'), ('cancelled', 'Annulée')], default='pending', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Montant total'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='current_location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Emplacement actuel'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parcels', to='parcels.order', verbose_name='Commande'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('in_transit', 'En transit'), ('out_for_delivery', 'En cours de livraison'), ('delivered', 'Livré'), ('exception', 'Exception'), ('consolidated', 'Consolidé')], default='pending', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Numéro de suivi'),
        ),
    ]
