# Generated by Django 6.0.6 on 2026-08-04 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0003_parcel_client_name_parcel_client_phone_parcel_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ville'),
        ),
        migrations.AddField(
            model_name='order',
            name='client_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom client'),
        ),
        migrations.AddField(
            model_name='order',
            name='client_phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Téléphone'),
        ),
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Commentaire'),
        ),
        migrations.AddField(
            model_name='order',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pays'),
        ),
        migrations.AddField(
            model_name='order',
            name='product_links',
            field=models.TextField(blank=True, null=True, verbose_name='Liens produits'),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantité'),
        ),
    ]
