# Generated by Django 6.0.6 on 2026-09-08 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0014_merge_20260906_0059'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsolidationNoteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='consolidations/', verbose_name='Image')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'upload")),
                ('consolidation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_images', to='parcels.consolidation', verbose_name='Groupage')),
            ],
            options={
                'verbose_name': 'Photo note groupage',
                'verbose_name_plural': 'Photos note groupage',
                'ordering': ['uploaded_at', 'id'],
            },
        ),
    ]
