# Generated by Django 6.0.6 on 2026-09-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0015_consolidation_note_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='consolidation',
            name='client_note',
            field=models.TextField(blank=True, default='', verbose_name='Description client (demande)'),
        ),
    ]
