# Generated by Django 6.0.6 on 2026-09-08 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0016_consolidation_client_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='consolidation',
            name='billable_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Poids facturable (kg)'),
        ),
        migrations.AddField(
            model_name='consolidation',
            name='grouping_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Frais de groupage (USD)'),
        ),
        migrations.AddField(
            model_name='consolidation',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Poids réel (kg)'),
        ),
    ]
