# Generated by Django 6.0.6 on 2026-09-19 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0024_alter_expeditionrequest_loyalty_discount_usd'),
        ('parcels', '0024_expedition_express_category'),
    ]

    operations = [
    ]
