# Generated by Django 6.0.6 on 2026-09-19 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        # Historique : branche loyalty (0023) + express category (0024).
        ('parcels', '0023_expedition_loyalty_discount'),
        ('parcels', '0024_expedition_express_category'),
    ]

    operations = [
    ]
