# Generated by Django 6.0.6 on 2026-09-26 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0025_merge_20260919_1100'),
        ('parcels', '0025_parcel_warehouse_location_help'),
    ]

    operations = [
    ]
