# Generated by Django 6.0.6 on 2026-10-05 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0026_merge_20260926_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expeditionrequest',
            name='shipping_category',
            field=models.CharField(blank=True, choices=[('ordinary', 'Colis ordinaire'), ('express', 'Express (colis ordinaire)'), ('sensitive', 'Colis sensibles'), ('phone', 'Téléphone'), ('computer', 'Ordinateur')], max_length=20, null=True, verbose_name="Catégorie d'expédition (avion)"),
        ),
    ]
